spring.application.name=hero-api

cors.allowed-origins=http://localhost:5500,http://127.0.0.1:5500,http://localhost:4200

spring.jpa.open-in-view=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

application.security.jwt.secret-key=CT3Pgx+8yN8Z3wwGjcdws8Uzxz28vTmBkhgrqLsXryA=
logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/hero_db
spring.datasource.username=brehcore
spring.datasource.password=QS01Cj0601

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brehcore@gmail.com
spring.mail.password=rkzzduilrfwqexap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000