CREATE TABLE tb_family (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           family_name VARCHAR(255) NOT NULL,
                           PRIMARY KEY (id)
);

CREATE TABLE tb_users (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          name VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          role VARCHAR(255) NOT NULL CHECK (role IN ('MONITOR','MINOR')),
                          family_id BIGINT,
                          PRIMARY KEY (id),
                          CONSTRAINT fk_user_family FOREIGN KEY (family_id) REFERENCES tb_family(id)
);

CREATE TABLE tb_wallet (
                           user_id BIGINT NOT NULL,
                           money_balances FLOAT(53) NOT NULL,
                           token_balances INTEGER NOT NULL,
                           PRIMARY KEY (user_id),
                           CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES tb_users(id)
);

CREATE TABLE tb_money_transaction (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      date TIMESTAMP(6),
                                      motive VARCHAR(255) NOT NULL,
                                      type VARCHAR(255) NOT NULL CHECK (type IN ('CREDIT','DEBIT')),
                                      value FLOAT(53) NOT NULL,
                                      wallet_id BIGINT NOT NULL,
                                      PRIMARY KEY (id),
                                      CONSTRAINT fk_money_wallet FOREIGN KEY (wallet_id) REFERENCES tb_wallet(user_id)
);

CREATE TABLE tb_token_transaction (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      date TIMESTAMP(6),
                                      motive VARCHAR(255) NOT NULL,
                                      type VARCHAR(255) NOT NULL CHECK (type IN ('CREDIT','DEBIT')),
                                      value INTEGER NOT NULL,
                                      wallet_id BIGINT NOT NULL,
                                      PRIMARY KEY (id),
                                      CONSTRAINT fk_token_wallet FOREIGN KEY (wallet_id) REFERENCES tb_wallet(user_id)
);

CREATE TABLE tb_tasks (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          approval_date TIMESTAMP(6),
                          completed_date TIMESTAMP(6),
                          creation_date TIMESTAMP(6),
                          description VARCHAR(255),
                          status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING','COMPLETED','APPROVED','REJECTED')),
                          title VARCHAR(255) NOT NULL,
                          token_raward INTEGER NOT NULL,
                          minor_id BIGINT NOT NULL,
                          monitor_creater_id BIGINT,
                          PRIMARY KEY (id),
                          CONSTRAINT fk_task_minor FOREIGN KEY (minor_id) REFERENCES tb_users(id),
                          CONSTRAINT fk_task_monitor FOREIGN KEY (monitor_creater_id) REFERENCES tb_users(id)
);